language: go

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libpulse-dev
    - libportaudio-dev
    - libportaudio2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio; fi

script:
  - make init
  - make test
  - make build

before_deploy:
  - make release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make release_windows; fi

deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    branch: release
  api-key:
    secure: aGv3j4FNrkqa3Fn04iE1JYl/0+ScC65hjthILuaKmfCdguSgAAN/HD8UYer9gfQaPKefS8VviTyqMiyo51TRLOelxOyUW4gM82q2m8Xi5xNb/067LIJurBqVz4pnfuSoAAwWBk4v96hlwWjz636dLAYMALBDb2B3eySRNYup+UNj82+WKJ3dsGrrQUXHHBgZ6NBHipgzsRxZA7NQ9w4AIO78eaDV20vZLDLkXTxPRG13cyZO2SitrdSzzrguaZu9Q6ZOAJnB8qkwXVysltSXeqrLqtAxM30HNtJUgavsvcmmC1A6VULNxQmETCv8io83VaqemtN158/SYjNXuQOfmLXqFlgxmzuDXIoCpEaqxdBxZcHRU9/GNJ2zoKDOZbtVlre3FFHlohe/1GTbpjj+6R3OJw3uiS+VO8YiSQNRaKXPohzAPWkg5g+hnvGCKSYuVFZKQYLIYc1PVHE66o7V5TxbrrnBviPIpnWDUIkrDIX9H/Fb13u0vzpUqQKZvkhiAhwf/62dgoRhDgZ2aDY2bXiC2ddPtfDiLAIgf+K5Z4A6Qx8kYfh/2uSCEbrQ32kSJuBmpLDW79G7OShAWKSyxzyiBXZ6/0MzF+S0qLF3e9uNPcVHt7QswZ+4Fmzgyc+78J+Xe5Qg4Nz375FTT4X/tprZOosvhaErBRGrlFwYIgw=
