language: go

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libpulse-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio; fi

script:
  - make init
  - make test
  - make build
